### ISSUE TITLE
AssertionError: indentSpaces: 2, tabSize: 4

### ISSUE THREAD

**Issue by BorzdeG** [dima74/intellij-indent-rainbow#11]
plugin version: 1.4.0

```
java.lang.AssertionError: indentSpaces: 2, tabSize: 4
	at indent.rainbow.IrFormatterAnnotatorImpl.highlight(IrFormatterAnnotatorImpl.kt:55)
	at indent.rainbow.IrFormatterAnnotatorImpl.runForLine(IrFormatterAnnotatorImpl.kt:44)
	at indent.rainbow.IrFormatterAnnotatorImpl.runForLines(IrFormatterAnnotatorImpl.kt:30)
	at indent.rainbow.annotators.IrFormatterIncrementalAnnotator.annotate(IrFormatterIncrementalAnnotator.kt:25)
	at com.intellij.codeInsight.daemon.impl.DefaultHighlightVisitor.runAnnotators(DefaultHighlightVisitor.java:129)
	at com.intellij.codeInsight.daemon.impl.DefaultHighlightVisitor.visit(DefaultHighlightVisitor.java:110)
	at com.intellij.codeInsight.daemon.impl.InjectedGeneralHighlightingPass.lambda$runHighlightVisitorsForInjected$5(InjectedGeneralHighlightingPass.java:368)
	at com.intellij.codeInsight.daemon.impl.DefaultHighlightVisitor.analyze(DefaultHighlightVisitor.java:93)
	at com.intellij.codeInsight.daemon.impl.InjectedGeneralHighlightingPass.runHighlightVisitorsForInjected(InjectedGeneralHighlightingPass.java:365)
	at com.intellij.codeInsight.daemon.impl.InjectedGeneralHighlightingPass.addInjectedPsiHighlights(InjectedGeneralHighlightingPass.java:242)
	at com.intellij.codeInsight.daemon.impl.InjectedGeneralHighlightingPass.lambda$addInjectedPsiHighlights$4(InjectedGeneralHighlightingPass.java:205)
	at com.intellij.concurrency.JobLauncherImpl.lambda$null$2(JobLauncherImpl.java:125)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:625)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:570)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:61)
	at com.intellij.concurrency.JobLauncherImpl.lambda$processImmediatelyIfTooFew$3(JobLauncherImpl.java:121)
	at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:865)
	at com.intellij.concurrency.JobLauncherImpl.processImmediatelyIfTooFew(JobLauncherImpl.java:132)
	at com.intellij.concurrency.JobLauncherImpl.invokeConcurrentlyUnderProgress(JobLauncherImpl.java:40)
	at com.intellij.concurrency.JobLauncher.invokeConcurrentlyUnderProgress(JobLauncher.java:49)
	at com.intellij.codeInsight.daemon.impl.InjectedGeneralHighlightingPass.addInjectedPsiHighlights(InjectedGeneralHighlightingPass.java:204)
	at com.intellij.codeInsight.daemon.impl.InjectedGeneralHighlightingPass.collectInformationWithProgress(InjectedGeneralHighlightingPass.java:91)
	at com.intellij.codeInsight.daemon.impl.ProgressableTextEditorHighlightingPass.doCollectInformation(ProgressableTextEditorHighlightingPass.java:84)
	at com.intellij.codeHighlighting.TextEditorHighlightingPass.collectInformation(TextEditorHighlightingPass.java:52)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$null$1(PassExecutorService.java:434)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1107)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$doRun$2(PassExecutorService.java:427)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:625)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:570)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:61)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.doRun(PassExecutorService.java:426)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$run$0(PassExecutorService.java:402)
	at com.intellij.openapi.application.impl.ReadMostlyRWLock.executeByImpatientReader(ReadMostlyRWLock.java:168)
	at com.intellij.openapi.application.impl.ApplicationImpl.executeByImpatientReader(ApplicationImpl.java:169)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.run(PassExecutorService.java:400)
	at com.intellij.concurrency.JobLauncherImpl$VoidForkJoinTask$1.exec(JobLauncherImpl.java:171)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:177)
```

IntelliJ IDEA 2020.1 EAP (Ultimate Edition)
Build #IU-201.6487.11, built on March 18, 2020
IntelliJ IDEA EAP User
Expiration date: April 17, 2020
Runtime version: 11.0.6+8-b765.15 x86_64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
macOS 10.15.4
GC: ParNew, ConcurrentMarkSweep
Memory: 1979M
Cores: 12
Non-Bundled Plugins: KotlinTIOBE, PlantUML integration, String Manipulation, com.ankit.mahadik.json.dart.class, com.github.leomillon.uuidgenerator, com.github.novotnyr.jwt-intellij-plugin, com.github.shchurov.gradlestop, com.idlesign.qrcoder, com.vladsch.git-file-case-fixer, zielu.gittoolbox, Lombook Plugin, com.herbert.george.dart.extensions, com.intellij.bigdecimal-folding, com.jetbrains.embeddedProjectJdk, com.viartemev.requestmapper, com.yhuang.code-smell-detector, de.docksnet.puml.syntaxchecker, launch-url-from-string, marcglasberg.HibernateInspectionsPlugin, org.jetbrains.plugins.hocon, org.pmesmeur.sketchit, woaini.liquibase.plugin, com.intellij.plugins.macoskeymap, com.blackbuild.intellij.maven-wrapper-support, com.intellij.selenium, com.sonnk.iterm, detekt, fr.dco.kotlin.vcs-kotlin-converter, hunspell, ideanginx9, in.thekalinga.snippet.intellij, indent-rainbow.indent-rainbow, name.kropp.intellij.makefile, org.intellij.RegexpTester, BashSupport, AWSCloudFormation, com.intellij.kubernetes, ru.adelf.idea.dotenv, Dart, andrasferenczi.dart-data-plugin, com.localizely.flutter-intl, com.mobiledi.flutter_plugins, io.flutter, org.jetbrains.kotlin, izhangzhihao.rainbow.brackets, com.layernet.plugin.adbwifi, net.aquadc.mike.plugin, cn.yiiguxing.plugin.translate, de.mariushoefler.flutter_enhancement_suite, com.gmail.blueboxware.extsee, com.intellij.bigdatatools, com.jetbrains.packagesearch.intellij-plugin, kotlin-i18n-write-action, kotlintest-plugin-intellij, net.lagerwey.cucumber-kotlin, com.intellij.lang.jsgraphql, lermitage.intellij.extra.icons, org.asciidoctor.intellij.asciidoc, org.apache.camel, org.semonte.intellij.swagger, ru.itbasis.plugins.intellij.hashGenerator

**Comment by dima74** [comment]
@BorzdeG Thank you for report! Could you please provide file on which exception occurs?

**Comment by dima74** [comment]
Starting from version 1.4.1 such errors no longer break highlighting. In particular plugin now just logs error instead of throwing an exception (though IntelliJ will still display that exception occurs).

**Comment by dima74** [comment]
@BorzdeG are you still encounter this problem? If yes could you please provide file on which exception occurs?

**Comment by BorzdeG** [comment]
No, I don’t see any obvious errors yet. If it appears - I will open a new issue with an example file
